//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.NeuralNetworkPVSM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.NeuralNetworkPVSM.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import numpy as np
        ///import random as rd
        ///print(&quot;Instance is &quot;)
        ///print(instance)
        ///result = [
        ///    4, 8, 3, 9, 2, 1, 6, 5, 7,
        ///    9, 6, 7, 3, 4, 5, 8, 2, 1,
        ///    2, 5, 1, 8, 7, 6, 4, 9, 3,
        ///    5, 4, 8, 1, 3, 2, 9, 7, 6,
        ///    7, 2, 9, 5, 6, 4, 1, 3, 8,
        ///    1, 3, 6, 7, 9, 8, 2, 4, 5,
        ///    3, 7, 2, 6, 8, 9, 5, 1, 4,
        ///    8, 1, 4, 2, 5, 3, 7, 6, 9,
        ///    6, 9, 5, 4, 1, 7, 3, 8, 2
        ///]
        ///exit(0)
        ///&apos;&apos;&apos;
        ///sudoku_solution = [
        ///    4, 8, 3, 9, 2, 1, 6, 5, 7,
        ///    9, 6, 7, 3, 4, 5, 8, 2, 1,
        ///    2, 5, 1, 8, 7, 6, 4, 9, 3, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string neuralnetwork_py {
            get {
                return ResourceManager.GetString("neuralnetwork.py", resourceCulture);
            }
        }
    }
}
